corrected unexpected Test Error
corrected the following error in tests:
ValueError: too many values to unpack (expected 2)

The reason was that only 2 variables where assigned to the function 'simulateViewFactors', which returns 3 variables.

A dummy variable was added to catch the unneeded value, and to avoid the error message.